### ISSUE TITLE
Can't click link button, and back button

### ISSUE THREAD

**Issue by bilalmalkoc** [ramon82/zuck.js#59] opened 2019-09-16 09:35 UTC
In new update can't click link and back button. Also screen flowing bug not fixed. Just test it long height (scrolling) page.

**Comment by helderscrolls** [comment] 2019-09-16 15:40
can confirm same issue here

**Comment by rodrigommelo** [comment] 2019-09-17 02:03
Same problem... Can't touch back button on Chrome for Android and "native back" even enabled does not work...

**Comment by michaelolem** [comment] 2019-09-17 02:04
Same problem... Can't touch back button on Chrome for Android and "native back" even enabled does not work...

**Comment by helderscrolls** [comment] 2019-09-17 07:09
I’ve managed to get it working on a real smartphone, for exemple on my iPhone XS Max on iOS 13 and using the latest version of Safari the button does work like intended it only seems to bug on desktop where you have to use the ESC key to leave the modal

**Comment by ramon82** [comment] 2019-10-14 03:16
Duplicate of #60

**Closed by ramon82** 2019-10-14 03:16 UTC
