### ISSUE TITLE
Plugin not working with videos on Safari (IPhone, Macbook)

### ISSUE THREAD

**Issue by khanfas47** [ramon82/zuck.js#24] opened 2018-07-27 14:42 UTC
Hi,

Plugin is not working with videos on IPhone (Safari), Macbook (Safari). Before video loads it jumps to next video.
Ref Url:
https://beta.halonet.io/main_zuck.php

**Comment by ramon82** [comment] 2018-10-13 06:10
Duplicate of #26

**Closed by ramon82** 2018-10-13 06:10 UTC
Labels: bug
